name: publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2.1.3
        with:
          node-version: '12.x'
        
      - name: clean install dependencies
        run: npm ci

      - name: compile and create vsix
        run: npm run package
      
      - name: publish to marketplace
        if: github.ref == 'refs/heads/master'
        run: npm run deploy ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
